---
homebrew_taps:
  - 'versent/homebrew-taps'
  - 'caskroom/cask'
  - 'jmespath/jmespath'
  - 'caskroom/fonts'

homebrew_packages:
  - { name: 'coreutils' }
  - { name: 'findutils' }
  - { name: 'bash' }
  - { name: 'bash-completion' }
  - { name: 'python' }
  - { name: 'pwgen' }
  - { name: 'keychain' }
  - { name: 'curl' }
  - { name: 'pinentry' }
  - { name: 'gist' }
  - { name: 'jq' }
  - { name: 'terraform' }
  - { name: 'awscli' }
  - { name: 'ansible' }
  - { name: 'dos2unix' }
  - { name: 'watch' }
  - { name: 'subversion' }
  - { name: 'swaks' }
  - { name: 'ipcalc' }
  - { name: 'packer' }
  - { name: 'mtr' }
  - { name: 'sqlite' }
  - { name: 'unrar' }
  - { name: 'urlview' }
  - { name: 'ssh-copy-id' }
  - { name: 'go' }
  - { name: 'wget' }
  - { name: 'livestreamer' }
  - { name: 'ffmpeg' }
  - { name: 'shellcheck' }
  - { name: 'libao', install_options: '--HEAD' }
  - { name: 'pianobar' }
  - { name: 'offlineimap' }
  - { name: 'mutt' }
  - { name: 'sshuttle' }
  - { name: 'unicreds' }
  - { name: 'httpie' }
  - { name: 'ghi' }
  - { name: 'rkhunter' }
  - { name: 'qrencode' }
  - { name: 'oath-toolkit' }
  - { name: 'jp' }
  - { name: 'zbar' }
  - { name: 'streamlink' }
  - { name: 'slackcat' }
  - { name: 'kubernetes-cli' }
  - { name: 'kops' }
  - { name: 'gnu-sed' }
  - { name: 'kubectx', install_options: '--with-short-names' }

homebrew_cask_packages:
  - { name: 'aws-vault' }
  - { name: 'consul-cli' }
  - { name: 'streamlink-twitch-gui' }
  - { name: 'spotify' }
  - { name: 'keybase' }
  - { name: 'vlc' }
  - { name: 'yakyak' }
  - { name: 'font-noto-color-emoji' }
